<?php
$subtotal=0;$discount=0;
foreach($cartItems as $item){$subtotal+=$item['price']*$item['quantity'];if(!empty($item['discount_price'])&&$item['discount_price']<$item['price'])$discount+=($item['price']-$item['discount_price'])*$item['quantity'];}
?>
<section class="yv-checkout-hero"><div class="container"><div class="breadcrumb"><a href="/">Ana Sayfa</a> / Sepet</div><h1><span>Sepetiniz</span> hazır.</h1><p>Seçtiğiniz hizmetleri kontrol edin ve güvenli ödeme adımına geçin.</p><div class="yv-steps"><div class="yv-step active"><span><?= icon('shopping-cart',14) ?></span><strong>1 · Sepet</strong><small>Ürünlerini gözden geçir</small></div><div class="yv-step"><span><?= icon('credit-card',14) ?></span><strong>2 · Ödeme</strong><small>Bilgileri tamamla</small></div><div class="yv-step"><span><?= icon('check',14) ?></span><strong>3 · Onay</strong><small>Siparişini oluştur</small></div></div></div></section>
<section class="yv-cart-page"><div class="container">
<?php if(empty($cartItems)): ?><div class="yv-commerce-card yv-empty"><div class="yv-empty-icon"><?= icon('shopping-cart',34) ?></div><h2>Sepetiniz boş</h2><p>İhtiyacınıza uygun hizmet paketlerini keşfedin ve kolayca sipariş oluşturun.</p><a class="yv-btn yv-btn-primary" href="/kategoriler">Hizmetleri keşfet <?= icon('arrow-right',12) ?></a></div>
<?php else: ?><div class="yv-commerce-layout">
 <div class="yv-commerce-card"><div class="yv-card-head"><h2><?= icon('shopping-cart',15) ?> Sepetindeki Hizmetler</h2><span class="yv-count-pill"><?= count($cartItems) ?> paket</span></div>
  <?php foreach($cartItems as $item): ?><div class="yv-cart-row"><div class="yv-cart-product"><div class="yv-cart-icon"><?= icon('package',18) ?></div><div><h3><a href="/paket/<?= e($item['slug']) ?>"><?= e($item['name']) ?></a></h3><p><?= e($item['short_description'] ?: 'Dijital hizmet paketi') ?></p></div></div><div class="yv-qty-pill"><?= (int)$item['quantity'] ?> adet</div><div class="yv-line-price"><?= money($item['line_total']) ?></div><form method="POST" action="/sepet/sil"><?= csrfField() ?><input type="hidden" name="key" value="<?= (int)$item['cart_key'] ?>"><button class="yv-remove" type="submit" aria-label="Kaldır"><?= icon('trash',14) ?></button></form></div><?php endforeach; ?>
  <div style="padding:14px 18px"><a class="yv-text-link" href="/kategoriler"><?= icon('arrow-left',11) ?> Alışverişe devam et</a></div>
 </div>
 <aside class="yv-commerce-card yv-summary"><h3><?= icon('file-text',15) ?> Sipariş Özeti</h3><div class="yv-summary-row"><span>Ara toplam</span><b><?= money($subtotal) ?></b></div><?php if($discount>0): ?><div class="yv-summary-row" style="color:#e84b79"><span>İndirim</span><b>-<?= money($discount) ?></b></div><?php endif; ?><div class="yv-summary-total"><span>Toplam</span><strong><?= money($total) ?></strong></div><a class="yv-summary-cta" href="/odeme"><?= icon('lock',14) ?> Güvenli Ödemeye Geç <?= icon('arrow-right',12) ?></a><div class="yv-secure-list"><div><?= icon('shield',13) ?> SSL ile güvenli ödeme</div><div><?= icon('zap',13) ?> Sipariş sonrası hızlı işlem</div><div><?= icon('headphones',13) ?> 7/24 destek</div></div></aside>
</div><?php endif; ?></div></section>